services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["3"]
              capabilities: [gpu]